### ISSUE TITLE
Does nothing. 0% CPU load, 1.7gig RAM usage. Nothing else.

### ISSUE THREAD

**Issue by SolsticeProjekt** [horenbergerb/FriendSimulator#10]
Is that supposed to be normal?

"Creating new model..." and then "TypedStorage is deprecated"-warnings,
which, afaik, can be ignored.

No load on CPU or GPU, no change of RAM usage, no nothing.

Running Python 3.10, Windows 10.

**Comment by SolsticeProjekt** [comment]
In case it matters, this was the output when I CTRL+C'd it.

Traceback (most recent call last):
```
  File "C:\py\FriendSimulator-master\training.py", line 111, in <module>
    config = yaml.safe_load(open('config.yaml'))['training']
  File "C:\py\FriendSimulator-master\training.py", line 42, in fine_tune_gpt2
    pt_model = GPT2LMHeadModel.from_pretrained(model_name)
  File "C:\python\lib\site-packages\transformers\models\auto\tokenization_auto.py", line 707, in from_pretrained
    return tokenizer_class_fast.from_pretrained(pretrained_model_name_or_path, *inputs, **kwargs)
  File "C:\python\lib\site-packages\transformers\tokenization_utils_base.py", line 1770, in from_pretrained
    resolved_vocab_files[file_id] = cached_file(
  File "C:\python\lib\site-packages\transformers\utils\hub.py", line 409, in cached_file
    resolved_file = hf_hub_download(
  File "C:\python\lib\site-packages\huggingface_hub\utils\_validators.py", line 120, in _inner_fn
    return fn(*args, **kwargs)
  File "C:\python\lib\site-packages\huggingface_hub\file_download.py", line 1270, in hf_hub_download
    with FileLock(lock_path):
  File "C:\python\lib\site-packages\filelock\_api.py", line 231, in __enter__
    self.acquire()
  File "C:\python\lib\site-packages\filelock\_api.py", line 199, in acquire
    time.sleep(poll_interval)
```
